import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, ButtonDock } from '@deandre-dock/buttons';
import styles from './Home.module.css';
const SaveIcon = () => (_jsxs("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z" }), _jsx("polyline", { points: "17 21 17 13 7 13 7 21" }), _jsx("polyline", { points: "7 3 7 8 15 8" })] }));
const TrashIcon = () => (_jsxs("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("polyline", { points: "3 6 5 6 21 6" }), _jsx("path", { d: "M19 6l-1 14H6L5 6" }), _jsx("path", { d: "M10 11v6M14 11v6" })] }));
const GenerateIcon = () => (_jsx("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: _jsx("polygon", { points: "13 2 3 14 12 14 11 22 21 10 12 10 13 2" }) }));
export function HomePage() {
    return (_jsxs("div", { className: styles.page, children: [_jsxs("section", { className: styles.hero, children: [_jsxs("h1", { className: styles.title, children: ["Botones que se adaptan", _jsx("br", {}), _jsx("span", { className: styles.accent, children: "a tu flujo de trabajo" })] }), _jsxs("p", { className: styles.subtitle, children: [_jsx("code", { children: "@deandre-dock/buttons" }), " \u2014 Un sistema de dise\u00F1o con un ButtonDock flotante que el usuario puede mover, fijar y anclar libremente en pantalla."] })] }), _jsxs("section", { className: styles.demo, children: [_jsx("h2", { className: styles.sectionTitle, children: "ButtonDock \u2014 pru\u00E9balo aqu\u00ED" }), _jsxs("p", { className: styles.hint, children: ["Arrastra el handle ", _jsx("strong", { children: "\u283F" }), " para mover la barra \u00B7 Usa el bot\u00F3n \uD83C\uDFE0 o su\u00E9ltala en su lugar para volver"] }), _jsx("div", { className: styles.dockZone, children: _jsxs(ButtonDock, { showMode: true, children: [_jsx(Button, { variant: "primary", leftIcon: _jsx(GenerateIcon, {}), children: "Generar" }), _jsx(Button, { variant: "secondary", leftIcon: _jsx(SaveIcon, {}), children: "Guardar" }), _jsx(Button, { variant: "danger", iconOnly: true, leftIcon: _jsx(TrashIcon, {}), "aria-label": "Eliminar" })] }) })] }), _jsxs("section", { className: styles.variants, children: [_jsx("h2", { className: styles.sectionTitle, children: "Variantes de Button" }), _jsxs("div", { className: styles.row, children: [_jsx(Button, { variant: "primary", children: "Primary" }), _jsx(Button, { variant: "secondary", children: "Secondary" }), _jsx(Button, { variant: "ghost", children: "Ghost" }), _jsx(Button, { variant: "danger", children: "Danger" })] }), _jsxs("div", { className: styles.row, children: [_jsx(Button, { variant: "primary", size: "xs", children: "XS" }), _jsx(Button, { variant: "primary", size: "sm", children: "SM" }), _jsx(Button, { variant: "primary", size: "md", children: "MD" }), _jsx(Button, { variant: "primary", size: "lg", children: "LG" })] }), _jsxs("div", { className: styles.row, children: [_jsx(Button, { variant: "primary", loading: true, children: "Cargando" }), _jsx(Button, { variant: "secondary", disabled: true, children: "Deshabilitado" }), _jsx(Button, { variant: "primary", leftIcon: _jsx(SaveIcon, {}), children: "Con \u00EDcono" }), _jsx(Button, { variant: "ghost", iconOnly: true, leftIcon: _jsx(TrashIcon, {}), "aria-label": "Eliminar" })] })] })] }));
}
//# sourceMappingURL=index.js.map